// Generated by https://quicktype.io

export interface CarModel {
    _id: ID;
    owner_id: string;
    borrower_id?: string;
    name: string;
    number: string;
    brand: string;
    price: number;
    yop: number;
    dt: number;
    iat: string;
    ito: string;
    picture: string;
    desc: string;
}

interface ID {
    $oid: string;
}
