// Generated by https://quicktype.io

export interface UserModel {
    _id:           ID;
    uname:         string;
    email:         string;
    phone_number:  string;
    adhaar_number: string;
    pass:          string;
    photo_id:      string;
    birthday:      string;
}

export interface ID {
    $oid: string;
}
